feat: fail don't skip publishing on version mismatch

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -26,18 +26,15 @@ jobs:
 
       - name: Compare tag and package.json version
         working-directory: contracts
-        id: compare-versions
         run: |
           PACKAGE_JSON_VERSION="v$(cat package.json | jq -r '.version')"
-          if [ "$PACKAGE_JSON_VERSION" = "${{ github.ref_name }}" ]; then
-            echo "matches=true" >> $GITHUB_OUTPUT
-          else
-            echo "matches=false" >> $GITHUB_OUTPUT
+          if [ "$PACKAGE_JSON_VERSION" != "${{ github.ref_name }}" ]; then
+            echo "::error version mismatch: package.json version (v$PACKAGE_JSON_VERSION) does not match tag (${{ github.ref_name }})"
+            exit 1
           fi
 
       - name: Publish to NPM
         uses: smartcontractkit/.github/actions/ci-publish-npm@4e934ced130f447eaf325d1d610c440517eb93e9 # ci-publish-npm@0.2.0
-        if: steps.compare-versions.outputs.matches == 'true'
         with:
           npm-token: ${{ secrets.FAKE_NPM_TOKEN }}
           github-token: ${{ secrets.GITHUB_TOKEN }}
